package com.analyzer.ui;

import com.analyzer.model.Student;
import com.analyzer.service.StudentService;
import com.analyzer.ui.CustomComponents.*;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import java.awt.*;
import java.util.List;

/**
 * VIVA EXPLANATION - OOP CONCEPT: COHESION AND MODULAR UI DESIGN
 * This panel is highly cohesive, focusing strictly on performance visualization.
 * 1. Custom Progress Indicators: Features vector-drawn progress bars to visually contrast subject scores.
 * 2. Visual Chips: Grade and prediction metrics are styled with contextual colors (Green for A/B,
 *    Yellow for Average, Red for Poor) dynamically.
 * 3. Advisor Recommendations: Pulls text suggestions generated by the StudentService logic
 *    and showcases them inside an alert card box.
 */
public class AnalysisPanel extends JPanel {

    private StudentService studentService;
    
    // Selection Table
    private JTable tblStudents;
    private DefaultTableModel tableModel;
    
    // Dynamic Cards (Stats)
    private JLabel lblTotalScore;
    private JLabel lblAverage;
    private JLabel lblGrade;
    private JLabel lblCategory;
    
    // Card containers to swap colors
    private RoundedPanel cardGrade;
    private RoundedPanel cardCategory;
    
    // Subject visual meters container
    private JPanel panelSubjectMeters;
    
    // Advisory Text Box
    private JTextPane txtAdvisory;
    private JLabel lblAdvisoryTitle;
    private RoundedPanel advisoryCard;

    public AnalysisPanel(StudentService studentService) {
        this.studentService = studentService;

        setLayout(new BorderLayout(20, 20));
        setOpaque(false);
        setBorder(new EmptyBorder(10, 10, 10, 10));

        // Assemble Left: Student Grid List
        JPanel leftContainer = new JPanel(new BorderLayout(15, 15));
        leftContainer.setOpaque(false);
        leftContainer.setPreferredSize(new Dimension(320, 0));

        RoundedPanel listCard = new RoundedPanel(16, CustomComponents.COLOR_CARD_BG);
        listCard.setLayout(new BorderLayout(15, 15));
        listCard.setBorder(new EmptyBorder(20, 20, 20, 20));

        JLabel lblListTitle = new JLabel("Select Student for Diagnostics");
        lblListTitle.setFont(new Font("Segoe UI", Font.BOLD, 16));
        lblListTitle.setForeground(CustomComponents.COLOR_PRIMARY);

        String[] columnNames = {"ID", "Student Name"};
        tableModel = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblStudents = new JTable(tableModel);
        tblStudents.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        tblStudents.setRowHeight(38);
        tblStudents.setShowGrid(false);
        tblStudents.setIntercellSpacing(new Dimension(0, 0));
        tblStudents.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblStudents.setBackground(Color.WHITE);

        JTableHeader header = tblStudents.getTableHeader();
        header.setFont(new Font("Segoe UI", Font.BOLD, 13));
        header.setBackground(CustomComponents.COLOR_BG_LIGHT);
        header.setForeground(CustomComponents.COLOR_TEXT_DARK);
        header.setPreferredSize(new Dimension(0, 40));

        tblStudents.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(
                    JTable table, Object value, boolean isSelected, 
                    boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                setBorder(new EmptyBorder(0, 12, 0, 12));
                if (isSelected) {
                    c.setBackground(new Color(239, 246, 255));
                    c.setForeground(CustomComponents.COLOR_PRIMARY);
                } else {
                    c.setBackground(Color.WHITE);
                    c.setForeground(CustomComponents.COLOR_TEXT_DARK);
                }
                return c;
            }
        });

        JScrollPane scrollPane = new JScrollPane(tblStudents);
        scrollPane.setBorder(BorderFactory.createLineBorder(CustomComponents.COLOR_BORDER, 1));
        scrollPane.getViewport().setBackground(Color.WHITE);

        listCard.add(lblListTitle, BorderLayout.NORTH);
        listCard.add(scrollPane, BorderLayout.CENTER);
        leftContainer.add(listCard, BorderLayout.CENTER);

        // Assemble Right: Performance Dashboard Cockpit
        JPanel cockpitPanel = new JPanel(new BorderLayout(15, 15));
        cockpitPanel.setOpaque(false);

        // 1. Upper Stats Metrics Row
        JPanel statsRow = new JPanel(new GridLayout(1, 4, 15, 0));
        statsRow.setOpaque(false);
        statsRow.setPreferredSize(new Dimension(0, 110));

        // Card A: Total Marks
        RoundedPanel cardTotal = new RoundedPanel(16);
        cardTotal.setLayout(new BorderLayout(0, 5));
        JLabel lblTotalTitle = new JLabel("TOTAL MARKS");
        lblTotalTitle.setFont(new Font("Segoe UI", Font.BOLD, 11));
        lblTotalTitle.setForeground(CustomComponents.COLOR_TEXT_MUTED);
        lblTotalScore = new JLabel("0.0 / 500");
        lblTotalScore.setFont(new Font("Segoe UI", Font.BOLD, 20));
        lblTotalScore.setForeground(CustomComponents.COLOR_TEXT_DARK);
        cardTotal.add(lblTotalTitle, BorderLayout.NORTH);
        cardTotal.add(lblTotalScore, BorderLayout.CENTER);

        // Card B: Average Percentage
        RoundedPanel cardAverage = new RoundedPanel(16);
        cardAverage.setLayout(new BorderLayout(0, 5));
        JLabel lblAvgTitle = new JLabel("AVERAGE MARKS");
        lblAvgTitle.setFont(new Font("Segoe UI", Font.BOLD, 11));
        lblAvgTitle.setForeground(CustomComponents.COLOR_TEXT_MUTED);
        lblAverage = new JLabel("0.00%");
        lblAverage.setFont(new Font("Segoe UI", Font.BOLD, 22));
        lblAverage.setForeground(CustomComponents.COLOR_PRIMARY);
        cardAverage.add(lblAvgTitle, BorderLayout.NORTH);
        cardAverage.add(lblAverage, BorderLayout.CENTER);

        // Card C: Assigned Grade Bubble
        cardGrade = new RoundedPanel(16);
        cardGrade.setLayout(new BorderLayout(0, 5));
        JLabel lblGradeTitle = new JLabel("LETTER GRADE");
        lblGradeTitle.setFont(new Font("Segoe UI", Font.BOLD, 11));
        lblGradeTitle.setForeground(CustomComponents.COLOR_TEXT_MUTED);
        lblGrade = new JLabel("Grade F");
        lblGrade.setFont(new Font("Segoe UI", Font.BOLD, 22));
        lblGrade.setForeground(CustomComponents.COLOR_TEXT_DARK);
        cardGrade.add(lblGradeTitle, BorderLayout.NORTH);
        cardGrade.add(lblGrade, BorderLayout.CENTER);

        // Card D: Rating category
        cardCategory = new RoundedPanel(16);
        cardCategory.setLayout(new BorderLayout(0, 5));
        JLabel lblCatTitle = new JLabel("PERFORMANCE RATIO");
        lblCatTitle.setFont(new Font("Segoe UI", Font.BOLD, 11));
        lblCatTitle.setForeground(CustomComponents.COLOR_TEXT_MUTED);
        lblCategory = new JLabel("POOR");
        lblCategory.setFont(new Font("Segoe UI", Font.BOLD, 20));
        lblCategory.setForeground(CustomComponents.COLOR_DANGER);
        cardCategory.add(lblCatTitle, BorderLayout.NORTH);
        cardCategory.add(lblCategory, BorderLayout.CENTER);

        statsRow.add(cardTotal);
        statsRow.add(cardAverage);
        statsRow.add(cardGrade);
        statsRow.add(cardCategory);

        cockpitPanel.add(statsRow, BorderLayout.NORTH);

        // 2. Middle Row: Split between Subject Score Meters and Diagnostic Advisory
        JPanel centerSplit = new JPanel(new GridLayout(1, 2, 15, 0));
        centerSplit.setOpaque(false);

        // Panel A: Subject Score Bars card
        RoundedPanel metersCard = new RoundedPanel(16, CustomComponents.COLOR_CARD_BG);
        metersCard.setLayout(new BorderLayout(10, 10));
        metersCard.setBorder(new EmptyBorder(15, 15, 15, 15));

        JLabel lblMeterTitle = new JLabel("📊 Subject Academic Performance Meters");
        lblMeterTitle.setFont(new Font("Segoe UI", Font.BOLD, 15));
        lblMeterTitle.setForeground(CustomComponents.COLOR_TEXT_DARK);
        lblMeterTitle.setBorder(new EmptyBorder(0, 0, 10, 0));

        panelSubjectMeters = new JPanel();
        panelSubjectMeters.setLayout(new BoxLayout(panelSubjectMeters, BoxLayout.Y_AXIS));
        panelSubjectMeters.setOpaque(false);

        metersCard.add(lblMeterTitle, BorderLayout.NORTH);
        metersCard.add(panelSubjectMeters, BorderLayout.CENTER);

        // Panel B: Advisory Card
        advisoryCard = new RoundedPanel(16, CustomComponents.COLOR_CARD_BG);
        advisoryCard.setLayout(new BorderLayout(10, 10));
        advisoryCard.setBorder(new EmptyBorder(15, 15, 15, 15));

        lblAdvisoryTitle = new JLabel("🎯 Smart Performance Advisory");
        lblAdvisoryTitle.setFont(new Font("Segoe UI", Font.BOLD, 15));
        lblAdvisoryTitle.setForeground(CustomComponents.COLOR_TEXT_DARK);

        txtAdvisory = new JTextPane();
        txtAdvisory.setEditable(false);
        txtAdvisory.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        txtAdvisory.setForeground(CustomComponents.COLOR_TEXT_DARK);
        txtAdvisory.setBackground(CustomComponents.COLOR_CARD_BG);
        txtAdvisory.setOpaque(false);

        JScrollPane advisoryScroll = new JScrollPane(txtAdvisory);
        advisoryScroll.setBorder(null);
        advisoryScroll.setOpaque(false);
        advisoryScroll.getViewport().setOpaque(false);

        advisoryCard.add(lblAdvisoryTitle, BorderLayout.NORTH);
        advisoryCard.add(advisoryScroll, BorderLayout.CENTER);

        centerSplit.add(metersCard);
        centerSplit.add(advisoryCard);

        cockpitPanel.add(centerSplit, BorderLayout.CENTER);

        // Assemble Main Panels
        add(leftContainer, BorderLayout.WEST);
        add(cockpitPanel, BorderLayout.CENTER);

        // Selection Listener
        tblStudents.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    handleSelectionChange();
                }
            }
        });

        // Initialize lists
        refreshTable();
        clearCockpit();
    }

    /**
     * Refreshes the student selector table list.
     */
    public void refreshTable() {
        tableModel.setRowCount(0);
        for (Student s : studentService.getAllStudents()) {
            tableModel.addRow(new Object[]{s.getId(), s.getName()});
        }
        clearCockpit();
    }

    /**
     * Clears metrics back to placeholder formats.
     */
    private void clearCockpit() {
        lblTotalScore.setText("- - / 500");
        lblAverage.setText("- -");
        lblGrade.setText("Grade -");
        lblCategory.setText("- -");
        
        cardGrade.setBackground(CustomComponents.COLOR_CARD_BG);
        cardCategory.setBackground(CustomComponents.COLOR_CARD_BG);
        
        panelSubjectMeters.removeAll();
        panelSubjectMeters.add(new JLabel("No student selected to plot metrics."));
        panelSubjectMeters.revalidate();
        panelSubjectMeters.repaint();

        txtAdvisory.setText("Select a student from the register roster grid on the left to review automated intelligence insights and advisor suggestions.");
        lblAdvisoryTitle.setForeground(CustomComponents.COLOR_TEXT_DARK);
        advisoryCard.setBorder(BorderFactory.createLineBorder(CustomComponents.COLOR_BORDER, 1));
    }

    /**
     * Executed when a row in the table is clicked: populates all statistical charts and recommendations dynamically.
     */
    private void handleSelectionChange() {
        int selectedRow = tblStudents.getSelectedRow();
        if (selectedRow == -1) {
            clearCockpit();
            return;
        }

        String id = tblStudents.getValueAt(selectedRow, 0).toString();
        Student s = studentService.getStudent(id);

        if (s == null) {
            clearCockpit();
            return;
        }

        // 1. Populate stats cards
        lblTotalScore.setText(String.format("%.1f / 500", s.getTotalMarks()));
        lblAverage.setText(String.format("%.2f%%", s.getAverageMarks()));
        lblGrade.setText("Grade " + s.getGrade());
        lblCategory.setText(s.getPerformanceCategory().toUpperCase());

        // 2. Color code cards based on performance (WOW premium feel)
        String cat = s.getPerformanceCategory();
        if (cat.equalsIgnoreCase("Excellent")) {
            lblCategory.setForeground(CustomComponents.COLOR_SUCCESS);
            lblGrade.setForeground(CustomComponents.COLOR_SUCCESS);
            advisoryCard.setBorder(BorderFactory.createLineBorder(CustomComponents.COLOR_SUCCESS, 2));
            lblAdvisoryTitle.setForeground(CustomComponents.COLOR_SUCCESS);
        } else if (cat.equalsIgnoreCase("Good")) {
            lblCategory.setForeground(CustomComponents.COLOR_PRIMARY);
            lblGrade.setForeground(CustomComponents.COLOR_PRIMARY);
            advisoryCard.setBorder(BorderFactory.createLineBorder(CustomComponents.COLOR_PRIMARY, 1));
            lblAdvisoryTitle.setForeground(CustomComponents.COLOR_PRIMARY);
        } else if (cat.equalsIgnoreCase("Average")) {
            lblCategory.setForeground(CustomComponents.COLOR_WARNING);
            lblGrade.setForeground(CustomComponents.COLOR_WARNING);
            advisoryCard.setBorder(BorderFactory.createLineBorder(CustomComponents.COLOR_WARNING, 1));
            lblAdvisoryTitle.setForeground(CustomComponents.COLOR_WARNING);
        } else {
            lblCategory.setForeground(CustomComponents.COLOR_DANGER);
            lblGrade.setForeground(CustomComponents.COLOR_DANGER);
            advisoryCard.setBorder(BorderFactory.createLineBorder(CustomComponents.COLOR_DANGER, 2));
            lblAdvisoryTitle.setForeground(CustomComponents.COLOR_DANGER);
        }

        // 3. Map out Subject graphical progress bars
        panelSubjectMeters.removeAll();
        panelSubjectMeters.setLayout(new GridLayout(5, 1, 0, 10));

        for (String subject : StudentService.SUBJECTS) {
            double score = s.getMark(subject);
            
            // Build custom progress meter row container
            JPanel rowPanel = new JPanel(new BorderLayout(10, 0));
            rowPanel.setOpaque(false);
            
            JLabel lblSub = new JLabel(subject);
            lblSub.setFont(new Font("Segoe UI", Font.BOLD, 12));
            lblSub.setForeground(CustomComponents.COLOR_TEXT_DARK);
            lblSub.setPreferredSize(new Dimension(130, 0));
            
            JLabel lblVal = new JLabel(String.format("%.1f", score));
            lblVal.setFont(new Font("Segoe UI", Font.BOLD, 12));
            lblVal.setForeground(CustomComponents.COLOR_TEXT_MUTED);
            lblVal.setPreferredSize(new Dimension(40, 0));

            // Custom painted flat progress bar inside row
            JProgressBar bar = new JProgressBar(0, 100);
            bar.setValue((int) score);
            bar.setStringPainted(false);
            bar.setBorderPainted(false);
            bar.setPreferredSize(new Dimension(0, 10));
            
            // Context color: pass vs warning
            if (score >= 50.0) {
                bar.setForeground(CustomComponents.COLOR_PRIMARY);
                bar.setBackground(new Color(239, 246, 255));
            } else {
                bar.setForeground(CustomComponents.COLOR_DANGER);
                bar.setBackground(new Color(254, 242, 242));
            }

            rowPanel.add(lblSub, BorderLayout.WEST);
            rowPanel.add(bar, BorderLayout.CENTER);
            rowPanel.add(lblVal, BorderLayout.EAST);

            panelSubjectMeters.add(rowPanel);
        }
        panelSubjectMeters.revalidate();
        panelSubjectMeters.repaint();

        // 4. Update Smart recommendations text
        txtAdvisory.setText(s.getSuggestions());
    }
}
